export const projects = [
  {
    id: "feat-1",
    title: "Projeto 1",
    description: "Breve descrição do Projeto 1. Placeholder até teres conteúdo final.",
    repoUrl: "#",
    languages: ["Java", "SQL"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: true,
  },
  {
    id: "feat-2",
    title: "Projeto 2",
    description: "Breve descrição do Projeto 2.",
    repoUrl: "#",
    languages: ["JavaScript", "HTML", "CSS"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: true,
  },
  {
    id: "feat-3",
    title: "Projeto 3",
    description: "Breve descrição do Projeto 3.",
    repoUrl: "#",
    languages: ["React", "Next.js", "Tailwind"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: true,
  },

  // resto (vai para a grelha encaixada)
  {
    id: "p-1",
    title: "Projeto 4",
    description: "Sistema de gestão de tarefas com C e Linux.",
    repoUrl: "#",
    languages: ["C", "Linux"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: false,
  },
  {
    id: "p-2",
    title: "Projeto 5",
    description: "Mini-dashboard com dados e filtros.",
    repoUrl: "#",
    languages: ["TypeScript", "UI"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: false,
  },
  {
    id: "p-3",
    title: "Projeto 6",
    description: "Rede neuronal simples em Python (placeholder).",
    repoUrl: "#",
    languages: ["Python", "AI"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: false,
  },
  {
    id: "p-4",
    title: "Projeto 7",
    description: "Ferramenta de automação/CLI.",
    repoUrl: "#",
    languages: ["Bash", "Linux"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: false,
  },
  {
    id: "p-5",
    title: "Projeto 8",
    description: "Projeto de redes e segurança (placeholder).",
    repoUrl: "#",
    languages: ["Redes", "Cybersecurity"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: false,
  },
  {
    id: "p-6",
    title: "Projeto 9",
    description: "App web com autenticação e páginas (placeholder).",
    repoUrl: "#",
    languages: ["Web", "Next.js"],
    cover: "/teste.png",
    demo: "/teste.png",
    featured: false,
  },
];

export const experience = [
  {
    role: "Engenharia Informática",
    date: "2024 — Presente",
    place: "Universidade Lusófona de Lisboa",
    desc: "Estudos e projetos práticos em programação, sistemas, redes e desenvolvimento, com foco crescente em cibersegurança e IA.",
    tags: ["Java", "C", "Redes", "Web"],
  },
  {
    role: "Aprendiz, Carpintaria Metálica",
    date: "2023 — Presente",
    place: "Trabalho / Formação",
    desc: "Trabalho prático com rigor e disciplina: leitura de medidas, execução e controlo de qualidade.",
    tags: ["Rigor", "Processo", "Equipa"],
  },
  {
    role: "Voluntariado Web Summit",
    date: "2025",
    place: "Eventos / Comunidade",
    desc: "Apoio a startups, speakers e investors, contacto com ambiente tecnológico.",
    tags: ["Comunicação", "Organização"],
  },
];

export const skills = [
  { name: "Linux", level: 80 },
  { name: "Cybersecurity", level: 75 },
  { name: "Java", level: 78 },
  { name: "JavaScript", level: 72 },
  { name: "SQL", level: 70 },
  { name: "AI", level: 62 },
  { name: "C", level: 68 },
  { name: "Web", level: 74 },
];